Adding calendar page

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,16 +1,16 @@
 #!/bin/sh
 
-# Run tests
-npm run test
-if [ $? -ne 0 ]; then
-    echo "Tests failed! Push aborted."
-    exit 1
-fi
-
 # Run lint
 npm run lint --fix
 if [ $? -ne 0 ]; then
     echo "Linting failed! Push aborted."
+    exit 1
+fi
+
+# Run tests
+npm run test
+if [ $? -ne 0 ]; then
+    echo "Tests failed! Push aborted."
     exit 1
 fi
 
